### PR TITLE
Re-Writing of Sharky_Sprint2_meeting7_Oct24.md

### PR DESCRIPTION
**Pull request by flyingbearxx**
Re-written the Meeting minutes about Oct 24's meeting after it was deleted purposefully by a team member.

### CODE REVIEW

**Review by khujista-01 — APPROVED** [review]
Reviewed and approved by khujista

**Review by yas176 — DISMISSED** [review]

**Review by raghdaelkei — APPROVED** [review]

**Comment by flyingbearxx** [comment]
Changes were once again, deleted by the Repository owner. The initial Team Meeting Minute was as shown in the screenshot below:  
Screenshot 2024-10-26 000450

**Comment by flyingbearxx** [comment]
The changes were once again deleted by the repository owner. Original meeting minute should be:  
image

**Comment by flyingbearxx** [comment]
The change= were once again deleted by the repository owner. Original meeting minute should be:  
Screenshot 2024-10-26 000450

**Comment by hlbels** [comment]
Teammate Shaili is lying about having a meeting, the only meeting during the lab was with the presence of the TA where progress was demostrated. Any other meeting the teammates did not inform me about in advance. Plus, Shaili insists on disgarding my work by writing that I have not finished my assigned work in the appropriate time. My work was over by Monday the 14th at 2AM documented in our WhatsApp group chat. I have also been providing guidance, fixing wrong commits, enhancing and debugging the code that my teammates commited while my work was technically over.

**Pull request closed without merging**
